// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyCRUDCORE.Models;

#nullable disable

namespace ProyCRUDCORE.Migrations
{
    [DbContext(typeof(DbcrudcoreContext))]
    partial class DbcrudcoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyCRUDCORE.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCargo")
                        .HasName("PK__CARGO__6C985625B08276AB");

                    b.ToTable("CARGO", (string)null);
                });

            modelBuilder.Entity("ProyCRUDCORE.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Correo")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("IdCargo")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__EMPLEADO__CE6D8B9E886D9E43");

                    b.HasIndex("IdCargo");

                    b.ToTable("EMPLEADO", (string)null);
                });

            modelBuilder.Entity("ProyCRUDCORE.Models.Empleado", b =>
                {
                    b.HasOne("ProyCRUDCORE.Models.Cargo", "oCargo")
                        .WithMany("Empleados")
                        .HasForeignKey("IdCargo")
                        .HasConstraintName("FK__EMPLEADO__IdCarg__398D8EEE");

                    b.Navigation("oCargo");
                });

            modelBuilder.Entity("ProyCRUDCORE.Models.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
